### PR TITLE
additional trigger ༼ つ ◕_◕ ༽つ

### PR DESCRIPTION
**Pull request by brianshumate**
make !turntup work as well

### CODE REVIEW

**Comment by hoobdeebla** [comment]
1) duplicate commits
2) !turntup works with only the !turnt trigger as the string turnt is inside turntup, regex will match both to !turnt as there's no check for the end of the trigger after !turnt
3) other than that it looks good

**Comment by brianshumate** [comment]
so close and do another, or?

**Comment by hoobdeebla** [comment]
those are just nitpicks, it gets the same end result regardless of the commits inside. i'm gonna let @omni5cience decide on this one. sorry for being such a slob brian :dog:

**Comment by brianshumate** [comment]
no worries!

**Comment by brianshumate** [comment]
not sure how i ended up with the dupe commits...

/me shakes fist at git and own brain

**Pull request closed without merging**
