### PR TITLE
set all the bots to have the same fingerprint for easy muting

### PR DESCRIPTION
**Pull request by llkats**
Not sure if setting the fingerprints all to the same thing has ramifications elsewhere, but I'm really tired of muting bots on a case-by-case basis. This change allows me to mute all the bots just once. Please let me know if this isn't as simple or breaks the bots somehow so I can look for another solution. Thanks!

### CODE REVIEW

**Comment by btford** [comment]
:+1:

**Comment by omni5cience** [comment]
This sounds perfectly reasonable.

That said, if we're going to send the same fingerprint for all the bots I think it would be better to just remove the fingerprint key from the bot.json file and set it in one place. Take a look at [lib/bot.js](https://github.com/omni5cience/meatspackles/blob/d9614316cf9e4af4cfaa5f20f38fe898dadfa529/lib/bot.js#L18)

**Comment by llkats** [comment]
Updated!

**Comment by omni5cience** [comment]
:shipit:

**Pull request merged**
